services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql_chat_db'
    environment:
      - 'MYSQL_DATABASE=examensarbetechatapp'
      - 'MYSQL_PASSWORD=my_password'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=spring_user'
    ports:
      - '3307:3306'

  app:
    image: 'chatapp_backend:latest'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'mysql'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql_chat_db:3306/examensarbetechatapp'
      - 'SPRING_DATASOURCE_USERNAME=spring_user'
      - 'SPRING_DATASOURCE_PASSWORD=my_password'
    ports:
      - '8080:8080'

